import type { SiteContent } from "./schema";

export const en: SiteContent = {
  locale: "en",
  meta: {
    title: "Simorgh AI Labs — AI, Photonics & Scientific Simulation",
    description:
      "Simorgh AI Labs is the studio of Fatemeh Shams, an AI engineer and physicist building intelligent simulations, fiber-optic sensor systems, scientific software, and automation for research teams and businesses.",
    keywords: [
      "AI engineer",
      "physicist",
      "fiber optic sensors",
      "scientific simulation",
      "machine learning consultant",
      "automation developer",
      "web design",
      "photonics",
    ],
  },
  nav: {
    home: "Home",
    about: "About",
    portfolio: "Portfolio",
    services: "Services",
    contact: "Contact",
    order: "Start a Project",
    cta: "Start a Project",
    brand: "Simorgh AI Labs",
    brandTagline: "Photonics × Physics × Machine Intelligence",
  },
  home: {
    hero: {
      eyebrow: "AI Engineering · Photonics · Scientific Computing",
      titleLine1: "Where light, physics",
      titleHighlight: "and intelligence",
      titleLine2: "converge into reality.",
      subtitle:
        "I'm Fatemeh Shams — an AI engineer and physicist designing intelligent simulations, fiber-optic sensor systems, and automated software for research labs, startups, and engineering teams.",
      ctaPrimary: "Start a Project",
      ctaSecondary: "View Portfolio",
      stats: [
        { value: "6+", label: "Years across physics & software" },
        { value: "30+", label: "Simulations & AI models shipped" },
        { value: "10+", label: "Sensor & automation systems built" },
      ],
      badges: ["Machine Learning", "Fiber Optic Sensing", "Physics Simulation", "Automation", "Web Engineering"],
    },
    introEyebrow: "Why Simorgh",
    introTitle: "One mind, three disciplines — fused into working systems",
    introBody:
      "Simorgh is the mythical bird of Persian legend, formed when countless birds discover they are, together, one greater intelligence. That's the idea behind this studio: physics, artificial intelligence, and software engineering are treated as one connected craft, not three separate jobs. The result is work that is scientifically rigorous, computationally sound, and genuinely useful in production.",
    features: [
      {
        title: "AI & Machine Learning",
        description:
          "Custom models, forecasting, anomaly detection, and LLM-powered tools trained on real scientific and business data.",
        icon: "brain",
      },
      {
        title: "Fiber Optic Sensing",
        description:
          "Signal processing and modeling for FBG, distributed acoustic sensing, and structural health monitoring systems.",
        icon: "fiber",
      },
      {
        title: "Scientific Simulation",
        description:
          "Physics-informed models and numerical simulations that turn equations into interactive, testable software.",
        icon: "atom",
      },
      {
        title: "Automation Pipelines",
        description:
          "Scripts and services that remove repetitive lab, data, and business workflows so your team can focus on the science.",
        icon: "automation",
      },
      {
        title: "Web & Product Design",
        description:
          "Modern, fast, bilingual websites and dashboards that present your research or business with credibility.",
        icon: "web",
      },
      {
        title: "Data & Visualization",
        description:
          "Dashboards and reporting tools that turn raw sensor and experiment data into clear, decision-ready insight.",
        icon: "chart",
      },
    ],
    portfolioTeaserTitle: "Selected Work",
    portfolioTeaserSubtitle: "A sample of AI, photonics, and engineering projects — case studies available on request.",
    processTitle: "How a project comes together",
    processSubtitle: "A clear, low-friction process from first message to delivered system.",
    processSteps: [
      { title: "Discovery Call", description: "We talk through your goals, data, and constraints — no jargon, no pressure." },
      { title: "Proposal & Scope", description: "You receive a clear scope, timeline, and price before anything is booked." },
      { title: "Build & Check-ins", description: "Regular updates while the model, sensor pipeline, or site takes shape." },
      { title: "Delivery & Support", description: "Final handover with documentation, plus support for the first weeks live." },
    ],
    ctaBannerTitle: "Have an idea, a dataset, or a sensor that needs to talk?",
    ctaBannerSubtitle: "Tell me about your project — most quote requests get a reply within 48 hours.",
    ctaBannerButton: "Request a Quote",
  },
  about: {
    eyebrow: "About Me",
    title: "Fatemeh Shams",
    intro: "AI Engineer & Physicist — building intelligent systems at the edge of light and computation.",
    bio: [
      "I work at the intersection of physics and artificial intelligence: training machine learning models, writing scientific simulations, and designing fiber-optic sensing systems that measure the physical world with light.",
      "My background in physics shapes how I approach every engineering problem — with a focus on first principles, measurement, and verifiable results rather than guesswork. That same rigor carries over into the software, automation, and websites I build for clients.",
      "Outside of client work, I spend time exploring physics-informed machine learning, distributed fiber-optic sensing, and tools that make scientific work faster and less repetitive.",
    ],
    photoAlt: "Portrait of Fatemeh Shams, AI engineer and physicist",
    skillsTitle: "Core Skills",
    skillGroups: [
      { title: "AI & Machine Learning", skills: ["Python", "PyTorch / TensorFlow", "LLM tooling & RAG", "Signal & time-series ML", "Computer vision"] },
      { title: "Physics & Photonics", skills: ["Fiber Bragg Gratings", "Distributed acoustic sensing", "Optical signal processing", "Numerical methods", "MATLAB / COMSOL"] },
      { title: "Software & Automation", skills: ["TypeScript / Next.js", "Node.js APIs", "Python automation", "Databases (SQL/Supabase)", "CI/CD & cloud deployment"] },
    ],
    educationTitle: "Education",
    education: [
      {
        period: "2019 — 2023",
        title: "M.Sc. in Physics",
        place: "Focus: Photonics & Applied Optics",
        description: "Research on optical sensing methods and signal analysis, with coursework in computational and condensed matter physics.",
      },
      {
        period: "2015 — 2019",
        title: "B.Sc. in Physics",
        place: "Core physics with a minor in computer science",
        description: "Built a foundation in classical and quantum physics alongside programming, numerical analysis, and scientific computing.",
      },
    ],
    experienceTitle: "Experience",
    experience: [
      {
        period: "2023 — Present",
        title: "Independent AI & Photonics Engineer",
        place: "Simorgh AI Labs",
        description: "Delivering AI models, fiber-optic sensor simulations, automation pipelines, and web platforms for research groups and businesses.",
      },
      {
        period: "2021 — 2023",
        title: "Research Assistant — Optical Sensing Lab",
        place: "University Physics Department",
        description: "Developed simulation and signal-processing tools for fiber-optic sensor experiments and structural monitoring studies.",
      },
    ],
    publicationsTitle: "Research & Writing",
    publications: [
      "Signal processing techniques for fiber Bragg grating temperature sensors",
      "Physics-informed machine learning for optical sensor calibration",
      "Notes on distributed acoustic sensing for structural health monitoring",
    ],
    resumeCta: "Download Full Résumé (PDF)",
  },
  services: {
    eyebrow: "What I Offer",
    title: "Services built on physics, AI, and clean engineering",
    subtitle:
      "From a single simulation to a full product build, every engagement starts with understanding the science and the goal before writing a line of code.",
    items: [
      {
        title: "AI & Machine Learning Projects",
        description: "Custom models and intelligent tools trained on your data — forecasting, anomaly detection, classification, and LLM-based assistants.",
        bullets: ["Model design & training", "Data pipeline & preprocessing", "Evaluation & deployment", "LLM / chatbot integrations"],
        startingPrice: "From $450",
        icon: "brain",
      },
      {
        title: "Fiber Optic Sensor Simulation",
        description: "Modeling and signal-processing for FBG, distributed sensing, and structural/temperature/strain monitoring systems.",
        bullets: ["Sensor response modeling", "Noise & signal analysis", "MATLAB / Python simulation", "Calibration algorithms"],
        startingPrice: "From $500",
        icon: "fiber",
      },
      {
        title: "Scientific Simulation & Physics Software",
        description: "Turning physical models and equations into interactive, verifiable simulation tools and research software.",
        bullets: ["Numerical modeling", "Physics-informed ML", "Simulation dashboards", "Research tooling"],
        startingPrice: "From $400",
        icon: "atom",
      },
      {
        title: "Automation & Workflow Scripts",
        description: "Automated pipelines that handle repetitive lab, data-entry, reporting, or business tasks reliably in the background.",
        bullets: ["Data pipeline automation", "Report generation", "API integrations", "Scheduled jobs & bots"],
        startingPrice: "From $250",
        icon: "automation",
      },
      {
        title: "Website & Product Design",
        description: "Modern, fast, bilingual (English/Persian) websites, portfolios, and dashboards designed to build trust and convert visitors.",
        bullets: ["Custom design & branding", "Next.js development", "Bilingual (EN/FA) support", "Payments & contact forms"],
        startingPrice: "From $350",
        icon: "web",
      },
      {
        title: "Data Dashboards & Visualization",
        description: "Clear, interactive dashboards that turn sensor readings and experiment logs into decisions your team can act on.",
        bullets: ["Custom dashboards", "Real-time data views", "Reporting & exports", "Alerting logic"],
        startingPrice: "From $300",
        icon: "chart",
      },
    ],
    processNote: "Prices are starting estimates — every quote is tailored after a short discovery call based on scope and timeline.",
    ctaTitle: "Not sure which service fits your project?",
    ctaSubtitle: "Send a short description of what you need — I'll reply with a clear recommendation and quote.",
    ctaButton: "Request a Quote",
  },
  portfolio: {
    eyebrow: "Selected Work",
    title: "Portfolio",
    subtitle: "A sample of AI, photonics, physics, and automation projects. Full case studies and code samples available on request.",
    filterAll: "All",
    viewCase: "View Case Study",
    backToPortfolio: "Back to Portfolio",
    projects: [
      {
        slug: "fbg-sensor-simulator",
        title: "Fiber Bragg Grating Sensor Simulator",
        category: "Photonics & Simulation",
        summary: "A physics-based simulator modeling temperature and strain response of FBG sensors, with an ML layer for noise correction.",
        description: [
          "Fiber Bragg Grating sensors shift their reflected wavelength in response to temperature and strain, but real-world readings are noisy and nonlinear. This project built a simulation engine that models the optical response of an FBG sensor under configurable physical conditions, then layered a machine learning correction model on top to recover clean measurements from noisy signals.",
          "The simulator is used to test calibration algorithms before deploying them on physical hardware, cutting lab iteration time significantly and catching edge cases that would be expensive to discover on real sensors.",
        ],
        tags: ["Physics Simulation", "Machine Learning", "Python", "Signal Processing"],
        role: "Research & Development",
        year: "2024",
        results: ["Reduced calibration error by an estimated 35% in simulation", "Cut hardware test iterations by half", "Reusable simulation core for future sensor models"],
        icon: "fiber",
      },
      {
        slug: "optical-sensor-ml-calibration",
        title: "Neural Network Calibration for Optical Sensors",
        category: "AI & Machine Learning",
        summary: "A neural network that learns nonlinear sensor drift patterns and auto-corrects readings in real time.",
        description: [
          "Optical sensors drift with temperature, age, and installation stress in ways that are hard to model analytically. This project trained a compact neural network on labeled calibration data to predict and correct that drift in real time, replacing a manual lookup-table calibration process.",
          "The model was designed to run efficiently on constrained hardware, with a lightweight architecture chosen specifically to fit an embedded deployment target.",
        ],
        tags: ["Machine Learning", "PyTorch", "Embedded AI", "Calibration"],
        role: "ML Engineering",
        year: "2024",
        results: ["Replaced manual calibration tables with a learned model", "Runs in real time on constrained hardware", "Adaptable to new sensor batches with light retraining"],
        icon: "brain",
      },
      {
        slug: "structural-health-dfos",
        title: "Distributed Fiber Optic Sensing for Structural Monitoring",
        category: "Photonics & AI",
        summary: "An anomaly-detection pipeline for distributed acoustic sensing data used in structural health monitoring.",
        description: [
          "Distributed fiber optic sensing turns an ordinary optical fiber into thousands of virtual sensors along its length, generating large volumes of acoustic and strain data. This project built a processing pipeline that filters, segments, and analyzes that data stream to flag anomalies indicating potential structural stress or damage.",
          "The pipeline combines classical signal processing with a machine learning anomaly detector, tuned to minimize false positives while staying sensitive to genuine early-warning signals.",
        ],
        tags: ["Distributed Sensing", "Anomaly Detection", "Signal Processing", "Python"],
        role: "Systems & Algorithm Design",
        year: "2023",
        results: ["Automated analysis of high-volume sensor streams", "Early flagging of anomalous structural signals", "Modular pipeline adaptable to other DAS use cases"],
        icon: "atom",
      },
      {
        slug: "lab-automation-pipeline",
        title: "AI-Assisted Lab Data Automation Pipeline",
        category: "Automation",
        summary: "An automated pipeline that ingests raw instrument data, cleans it, and generates ready-to-review reports.",
        description: [
          "Research teams often lose hours each week to manually collecting, cleaning, and formatting instrument data. This project automated that entire chain: a script watches for new data files, validates and cleans them, runs standard analyses, and produces a formatted report — all without manual intervention.",
          "The system also includes lightweight anomaly flags so unusual readings are surfaced to the team immediately instead of being buried in a spreadsheet.",
        ],
        tags: ["Automation", "Python", "Data Pipelines", "Reporting"],
        role: "Automation Engineering",
        year: "2023",
        results: ["Saved an estimated 5+ hours per week of manual work", "Standardized report format across the team", "Immediate flagging of outlier readings"],
        icon: "automation",
      },
      {
        slug: "sensor-dashboard",
        title: "Real-Time Sensor Data Dashboard",
        category: "Web & Data",
        summary: "A live web dashboard visualizing multi-channel sensor data streams with alerting and historical playback.",
        description: [
          "Raw sensor logs are hard to act on without a clear interface. This project delivered a web dashboard that streams live multi-channel sensor data, renders it as interactive charts, and lets users scrub back through historical readings to investigate specific events.",
          "Built with a focus on performance and clarity, the dashboard also includes configurable threshold alerts so teams are notified the moment a reading moves out of range.",
        ],
        tags: ["Next.js", "Data Visualization", "Realtime", "Dashboards"],
        role: "Full-Stack Development",
        year: "2023",
        results: ["Real-time visualization of multi-channel data", "Configurable alerting on threshold breaches", "Historical playback for incident investigation"],
        icon: "chart",
      },
      {
        slug: "research-ai-assistant",
        title: "Custom AI Research Assistant",
        category: "AI & Automation",
        summary: "An LLM-powered assistant that answers questions over a lab's internal papers, notes, and datasets.",
        description: [
          "Research groups accumulate years of papers, notes, and datasets that become hard to search. This project built a retrieval-augmented assistant that indexes a lab's internal documents and answers natural-language questions with citations back to the source material.",
          "The assistant was designed with clear guardrails so it states uncertainty rather than fabricating results — an essential requirement for scientific use.",
        ],
        tags: ["LLM", "RAG", "AI Assistant", "Automation"],
        role: "AI Engineering",
        year: "2024",
        results: ["Faster retrieval across years of internal research", "Answers grounded with source citations", "Guardrails against fabricated scientific claims"],
        icon: "brain",
      },
    ],
  },
  contact: {
    eyebrow: "Get in Touch",
    title: "Let's talk about your project",
    subtitle: "Questions, collaborations, or just want to say hello — send a message and I'll get back to you within 48 hours.",
    formName: "Full Name",
    formEmail: "Email Address",
    formSubject: "Subject",
    formMessage: "Message",
    formSubmit: "Send Message",
    formSubmitting: "Sending...",
    formSuccess: "Thanks — your message has been sent. I'll reply soon.",
    formError: "Something went wrong. Please try again or email me directly.",
    directTitle: "Direct Contact",
    directEmail: "Email",
    directLocation: "Based in",
    locationValue: "Iran — working with clients worldwide",
  },
  order: {
    eyebrow: "Start a Project",
    title: "Request a Quote",
    subtitle: "Tell me about your project and I'll follow up with a clear scope, timeline, and price — usually within 48 hours.",
    steps: ["Fill in the details below", "Get a reply with scope & price", "Optionally reserve your spot with a deposit"],
    formName: "Full Name",
    formEmail: "Email Address",
    formPhone: "Phone (optional)",
    formServiceType: "Service Type",
    serviceOptions: [
      "AI & Machine Learning",
      "Fiber Optic Sensor Simulation",
      "Scientific Simulation / Physics Software",
      "Automation & Workflow Scripts",
      "Website & Product Design",
      "Data Dashboard & Visualization",
      "Something else",
    ],
    formBudget: "Estimated Budget",
    budgetOptions: ["Under $300", "$300 – $700", "$700 – $1,500", "$1,500 – $3,000", "$3,000+", "Not sure yet"],
    formTimeline: "Desired Timeline",
    timelineOptions: ["As soon as possible", "Within 2–4 weeks", "1–2 months", "Flexible / no rush"],
    formDescription: "Project Description",
    formDescriptionPlaceholder: "What are you trying to build or solve? Include any data, sensors, or systems involved.",
    depositNote: "Optional: reserve your project slot now with a small deposit. This is not required — you can also just submit the request and pay later after we agree on scope.",
    formSubmit: "Submit Request",
    formSubmitting: "Submitting...",
    formSuccessTitle: "Request received!",
    formSuccessBody: "Thanks — your project request has been sent. I'll review it and reply by email within 48 hours with next steps.",
    formError: "Something went wrong submitting your request. Please try again or email me directly.",
    payNow: "Pay Deposit Now",
    paySkip: "Submit Without Paying",
  },
  footer: {
    tagline: "AI engineering, photonics, and scientific software — built with rigor.",
    rights: "All rights reserved.",
    quickLinksTitle: "Quick Links",
    contactTitle: "Contact",
    legalPrivacy: "Privacy Policy",
    legalTerms: "Terms of Service",
  },
  legal: {
    privacyTitle: "Privacy Policy",
    privacyBody: [
      "This Privacy Policy explains how Simorgh AI Labs (\"we\", \"us\") collects, uses, and protects information when you visit this website or submit a form.",
      "Information We Collect: When you use the contact or project request forms, we collect the details you provide, such as your name, email address, phone number, and project description. We do not collect this information through any means other than forms you voluntarily submit.",
      "How We Use Information: Submitted information is used solely to respond to your inquiry, prepare a project quote, and communicate about a potential or active project. We do not sell or rent your information to third parties.",
      "Data Storage: Form submissions are stored securely using Supabase, a hosted database provider, and are accessible only to the site owner.",
      "Payments: If you choose to pay a deposit through our payment gateway, payment processing is handled entirely by the third-party payment provider. We do not store your card or payment credentials on our servers.",
      "Cookies & Analytics: This site may use minimal cookies or analytics tools to understand site traffic and improve the experience. You can control cookie behavior through your browser settings.",
      "Advertising: This site may display advertisements served by third-party advertising networks, such as Google AdSense, which may use cookies to serve ads based on your prior visits to this or other websites. You can opt out of personalized advertising through your ad settings.",
      "Your Rights: You may request access to, correction of, or deletion of your personal information at any time by contacting us via the contact page.",
      "Changes: This policy may be updated periodically. Continued use of the site after changes constitutes acceptance of the updated policy.",
    ],
    termsTitle: "Terms of Service",
    termsBody: [
      "By using this website and submitting a project or contact request, you agree to the following terms.",
      "Services: Descriptions of services and portfolio work on this site are for informational purposes. Actual project scope, timeline, and pricing are confirmed in writing after a discovery conversation.",
      "Quotes & Payments: Any starting prices listed are estimates only and are not binding offers. Deposits paid to reserve a project slot are applied toward the final project cost, as agreed in writing before payment.",
      "Refunds: Deposit refund terms are agreed upon individually per project and communicated before payment is made.",
      "Intellectual Property: Portfolio items shown on this site remain the intellectual property of their respective creators/clients and are shown for demonstration purposes with permission where required.",
      "Limitation of Liability: Services are provided on a best-effort professional basis. We are not liable for indirect, incidental, or consequential damages arising from use of delivered software or this website.",
      "Governing Terms: These terms are governed by applicable local law and may be updated at any time; continued use of the site constitutes acceptance of the current terms.",
    ],
  },
  common: {
    switchLang: "فارسی",
    langName: "English",
    notFoundTitle: "Page not found",
    notFoundBody: "The page you're looking for doesn't exist or may have moved.",
    notFoundCta: "Back to Home",
  },
};
